# Generated by Django 4.2.6 on 2023-10-29 00:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('ingredientes', models.TextField()),
                ('preparo', models.TextField()),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
